import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import axiosInstance from "@/api/axiosInstance";

// Fetch all deliverables with customer & service info
export const fetchAllDeliverables = createAsyncThunk(
  "deliverables/fetchAll",
  async (_, { rejectWithValue }) => {
    try {
      const res = await axiosInstance.get("/operations/upload/all/deliverable");
      return res.data.data;
    } catch (err) {
      return rejectWithValue(err.response?.data?.message || "Error fetching deliverables");
    }
  }
);

// Fetch deliverables for a specific order
export const fetchDeliverablesForOrder = createAsyncThunk(
  "deliverables/fetchByOrder",
  async (orderId, { rejectWithValue }) => {
    try {
      const res = await axiosInstance.get(`/operations/upload/deliverable/${orderId}`);
      return res.data.data;
    } catch (err) {
      return rejectWithValue(err.response?.data?.message || "Error fetching deliverables");
    }
  }
);


// 4️⃣ Deliverable by ID
export const fetchDeliverableById = createAsyncThunk(
  "operations/fetchDeliverableById",
  async (id, { rejectWithValue }) => {
    try {
      const res = await axiosInstance.get(
        `/operations/upload/deliverablebyid/${id}`
      );
      return res.data.data;
    } catch (err) {
      return rejectWithValue(
        err.response?.data?.message || "Error loading deliverable"
      );
    }
  }
);

// 6️⃣ Deliverables generated by logged-in operation
export const fetchDeliverablesByOperation = createAsyncThunk(
  "operations/fetchDeliverablesByOperation",
  async (_, { rejectWithValue }) => {
    try {
      const res = await axiosInstance.get(
        "/operations/deliverables/by-operation"
      );
      return res.data.data;
    } catch (err) {
      return rejectWithValue(
        err.response?.data?.message || "Error loading deliverables"
      );
    }
  }
);

// 7️⃣ Dashboard stats
export const fetchOperationDashboardStats = createAsyncThunk(
  "operations/fetchDashboardStats",
  async (_, { rejectWithValue }) => {
    try {
      const res = await axiosInstance.get("/operations/dashboard/stats");
      return res.data.data;
    } catch (err) {
      return rejectWithValue(
        err.response?.data?.message || "Error loading dashboard stats"
      );
    }
  }
);

const operationDeliverablesSlice = createSlice({
  name: "deliverables",
  initialState: {
    allDeliverables: [],
    orderDeliverables: [],
    deliverableById: null,
    myDeliverables: [],
    // Dashboard
        dashboardStats: null,
    loading: false,
    error: null,
  },
  reducers: {
    clearDeliverablesError: (state) => {
      state.error = null;
    },
    resetDeliverables: (state) => {
      state.allDeliverables = [];
      state.orderDeliverables = [];
       state.deliverableById = null;
       state.myDeliverables = [];
       state.dashboardStats = null;
      state.loading = false;
      state.error = null;
    },
  },
 extraReducers: (builder) => {
  builder
    /* ---------- Fetch all deliverables ---------- */
    .addCase(fetchAllDeliverables.pending, (state) => {
      state.loading = true;
      state.error = null;
    })
    .addCase(fetchAllDeliverables.fulfilled, (state, action) => {
  state.loading = false;
  state.allDeliverables = Array.isArray(action.payload)
    ? action.payload
    : [];
})

    .addCase(fetchAllDeliverables.rejected, (state, action) => {
      state.loading = false;
      state.error = action.payload;
    })

    /* ---------- Deliverables by order ---------- */
    .addCase(fetchDeliverablesForOrder.pending, (state) => {
      state.loading = true;
      state.error = null;
    })
    .addCase(fetchDeliverablesForOrder.fulfilled, (state, action) => {
      state.loading = false;
      state.orderDeliverables = action.payload;
    })
    .addCase(fetchDeliverablesForOrder.rejected, (state, action) => {
      state.loading = false;
      state.error = action.payload;
    })

    /* ---------- Deliverable by ID ---------- */
    .addCase(fetchDeliverableById.fulfilled, (state, action) => {
      state.deliverableById = action.payload;
    })

    /* ---------- My Deliverables (Operation) ---------- */
    .addCase(fetchDeliverablesByOperation.pending, (state) => {
      state.loading = true;
    })
    .addCase(fetchDeliverablesByOperation.fulfilled, (state, action) => {
      state.loading = false;
      state.myDeliverables = action.payload;
    })
    .addCase(fetchDeliverablesByOperation.rejected, (state, action) => {
      state.loading = false;
      state.error = action.payload;
    })

    /* ---------- Dashboard ---------- */
    .addCase(fetchOperationDashboardStats.fulfilled, (state, action) => {
      state.dashboardStats = action.payload;
    });
},

});

export const { clearDeliverablesError, resetDeliverables } = operationDeliverablesSlice.actions;
export default operationDeliverablesSlice.reducer;
